version: '3'

services:
  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
      - dataauth:/var/lib/mysql
    ports:
      - 3008:3006
    networks:
      - authentication
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - authentication
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
      - 5000:5000
    networks:
      - authentication
  applicationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - authentication
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - appdata:/var/lib/mysql
    ports:
      - 3009:3006
    networks:
      - application
  applicationDBMigration:
    image: applicationdbmigration
    environment:
      - DATABASE_URL=applicationDB
    depends_on:
      applicationDB:
        condition: service_healthy
    networks:
      - application
  owner:
    image: owner
    environment:
      - DATABASE_URL=applicationDB
    depends_on:
      - applicationDBMigration
    ports:
      - 5001:5001
    networks:
      - application
  customer:
    image: customer
    environment:
      - DATABASE_URL=applicationDB
    depends_on:
      - applicationDBMigration
    ports:
      - 5002:5002
    networks:
      - application
      - netblockchain
  courier:
    image: courier
    environment:
      - DATABASE_URL=applicationDB
    depends_on:
      - applicationDBMigration
    ports:
      - 5003:5003
    networks:
      - application
      - netblockchain
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - application
  spark-worker-1:
      image: bde2020/spark-worker:3.3.0-hadoop3.3
      container_name: spark-worker-1
      depends_on:
        - spark-master
      ports:
        - "8081:8081"
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"
      networks:
        - application
  spark-worker-2:
      image: bde2020/spark-worker:3.3.0-hadoop3.3
      container_name: spark-worker-2
      depends_on:
        - spark-master
      ports:
        - "8082:8081"
      environment:
        - "SPARK_MASTER=spark://spark-master:7077"
      networks:
        - application
  spark-history-server:
      image: bde2020/spark-history-server:3.3.0-hadoop3.3
      container_name: spark-history-server
      depends_on:
        - spark-master
      ports:
        - "18081:18081"
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events
      networks:
        - application
  owner_spark:
    image: owner_spark
    environment:
      - DATABASE_URL=applicationDB
    ports:
      - 5004:5004
    networks:
      - application
  ganache:
    image: trufflesuite/ganache
    environment:
      - DATABASE_URL=applicationDB
    ports:
      - 8545:8545
    networks:
      - netblockchain

volumes:
  dataauth:
  appdata:

networks:
  authentication:
  application:
  netblockchain: